default:
  installType: learning # learning or debug
  docker:
    #openmcpImageRepository: localhost:5000/openmcp
    istioImageRepository: localhost:5000/openmcp
    openmcpImageRepository: ketidevit2
    #istioImageRepository: docker.io
    imagePullSecretName: regcred
    imagePullPolicy: IfNotPresent # Always or IfNotPresent
master:
  ServerIP:
    internal: 10.0.3.60
    external: 115.94.141.62
    nfsmount: /home/nfs
  metalLB:
    rangeStartIP: 172.18.255.200
    rangeEndIP: 172.18.255.250
  Moudules:
    # LoadBalancingController 이외에는 모든 모듈의 IP가 같아도 상관없음
    # 위의 MetalLB의 IP 대역 범위 내에 모듈의 LoadBalancerIP 입력
    # MetricCollector는 멤버클러스터 gke, eks, aks의 접근이 가능해야 하므로 외부 IP 포트포워딩 필요
    # MetricCollector의 포트포워딩 설정 Example (115.94.141.62:3212 -> 10.0.3.20:30002)
    APIServer:
      NodePort: 30000
      AppKey: openmcp-apiserver
      UserName: openmcp
      UserPW: keti
    AnalyticEngine:
      NodePort: 30001
    MetricCollector:
      NodePort: 30002
      externalPort: 3212 # 115.94.141.62:3212 (MetricCollector는 멤버클러스터 gke, eks, aks의 접근이 가능해야 하므로 외부 IP 가 필요)
    InfluxDB:
      userName: root
      password: root
      NodePort: 30003
    LoadBalancingController:
      external: 115.94.141.62 #무조건 80포트 사용해야함.( Routing 규칙 필요시 외부포트80)
      NodePort: 30004
    postgresql:
      user: porsgres
      password: postgres123
      NodePort: 30901
      dbname: portal-controller
    portalapi:
      NodePort: 30902
externalServer:
  ServerIP:
    internal: 10.0.3.60
    external: 115.94.141.62
  powerDNS:
    apiKey: 1234
    externalPort: 5353 # Member클러스터의 접근을위해 DNS PORT 53을 포트포워딩 (115.94.141.62:5353 -> 10.0.3.12:53)


      
    
