apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPPolicy
metadata:
  name: predictive-scaling
  namespace: openmcp
spec:
  template:
    spec:
      targetController:
        kind: LSTM
      policies:
        - type: Status
          value:
            - "Enable"
  policyStatus: Enabled
