apiVersion:  openmcp.k8s.io/v1alpha1
kind: OpenMCPIngress
metadata:
  name: openmcp-ingress-example
  namespace: openmcp
spec:
  template:
    spec:
      rules:
      - host: openmcp.ingress.example.org
        http:
          paths:
          - backend:
              serviceName: openmcp-service-example
              servicePort: 80
      - host: openmcp.ingress.example.org2
        http:
          paths:
          - backend:
              serviceName: openmcp-service-example2
              servicePort: 80
