apiVersion: openmcp.k8s.io/v1alpha1
kind: Migration
metadata:
  name: migrations3
spec:
  migrationServiceSource:
  - sourceCluster: cluster01
    targetCluster: cluster02
    nameSpace: testmig
    serviceName: testmig2
    migrationSource:
    - resourceName: testmig2-dp
      resourceType: Deployment
    - resourceName: testmig2-sv
      resourceType: Service
