apiVersion: openmcp.k8s.io/v1alpha1
kind: Migration
metadata:
  name: migrations1
spec:
  migrationServiceSource:
  - sourceCluster: cluster02
    targetCluster: cluster03
    nameSpace: openmcp
    serviceName: testmig
    migrationSource:
    - resourceName: testmig-dp
      resourceType: Deployment
    - resourceName: testmig-sv
      resourceType: Service
