apiVersion: apps/v1
kind: Deployment
metadata: 
  name: testmig1-dp
  namespace: openmcp
  labels: 
    name: testmig1-dp
    app: testmig1
spec: 
  selector: 
    matchLabels: 
      app: testmig1
  template: 
    metadata: 
      labels: 
        app: testmig1
    spec: 
      containers: 
      - name: testmig1
        image: nginx:latest
        # command: ["sh", "-c", "chmod a+x /entrypoint.sh; /entrypoint.sh; sleep 100000000;"]
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 80
        env: 
          - name: DOCKER_HOST
            value: tcp://localhost:2375 
---
apiVersion: v1
kind: Service
metadata: 
  name: testmig1-sv
  namespace: openmcp
  labels: 
    name: testmig1-sv
    app: testmig1
spec: 
  type: NodePort
  ports: 
  - name: testmig1-web
    port: 31327
    targetPort: 80
    protocol: TCP
    nodePort: 31327
  selector: 
    app: testmig1
