apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-metric-collector
  namespace: openmcp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: cluster-metric-collector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: cluster-metric-collector
    spec:
      containers:
      - command:
        - cluster-metric-collector
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: GRPC_SERVER
          value: 115.94.141.62
        - name: GRPC_PORT
          value: "3212"
        - name: CLUSTER_NAME
          value: cluster12
        - name: OPERATOR_NAME
          value: openmcp-metric-collector
        image: ketidevit2/cluster-metric-collector:v0.0.1
        imagePullPolicy: Always
        name: cluster-metric-collector
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cluster-metric-collector
      serviceAccountName: cluster-metric-collector
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        tolerationSeconds: 0
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        tolerationSeconds: 0
