apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-api-server-cert
  labels:
    app: apiserver
spec:
  capacity:
    storage: 2Gi
  storageClassName: apiserver
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/cert"

