apiVersion: openmcp.k8s.io/v1alpha1
kind: Snapshot
metadata:
  name: test-snapshot
spec:
  snapshotSources:
  - resourceCluster: cluster02
    resourceNamespace: openmcp
    resourceType: Deployment
    resourceName: snapshot-dp
  - resourceCluster: cluster02
    resourceNamespace: openmcp
    resourceType: Service
    resourceName: snapshot-sv
