apiVersion: openmcp.k8s.io/v1alpha1
kind: Snapshot
metadata:
  name: testmig-snapshot
spec:
  snapshotSources:
  - resourceCluster: cluster2
    resourceNamespace: openmcp
    resourceType: Deployment
    resourceName: testmig-dp
  - resourceCluster: cluster2
    resourceNamespace: openmcp
    resourceType: Service
    resourceName: testmig-sv
#  - resourceCluster: cluster1
#    resourceNamespace: default
#    resourceType: PersistentVolume
#    resourceName: iot-gateway-pv
#  - resourceCluster: cluster1
#    resourceNamespace: default
#    resourceType: PersistentVolumeClaim
#    resourceName: iot-gateway-pvc
