apiVersion: openmcp.k8s.io/v1alpha1
kind: SnapshotRestore
metadata:
  name: example-snapshotrestore
spec:
  groupSnapshotKey: "1638515789"
  isGroupSnapshot: false
  snapshotRestoreSource:
  - resourceCluster: cluster2
    resourceNamespace: openmcp
    resourceType: Deployment
    resourceSnapshotKey: openmcp/snapshot/1624521742/cluster2/Deployment/testmig-dp
  - resourceCluster: cluster2
    resourceNamespace: openmcp
    resourceType: Service
    resourceSnapshotKey: openmcp/snapshot/1624521742/cluster2/Service/testmig-sv
