apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPDeployment
metadata:
  name: test-pod
#  namespace: keti
spec:
  replicas: 5
  labels:
      app: test-pod
  template:
    spec:
      template:
        spec:
          containers:
          - image: k8s.gcr.io/hpa-example
            ports:
            - containerPort: 80
            name: php-apache
            resources:
              requests:
                memory: 10Mi
                cpu: 100m
