apiVersion:  openmcp.k8s.io/v1alpha1
kind: OpenMCPIngress
metadata:
  name: test-ingress
#  namespace: openmcp
spec:
  template:
    spec:
      rules:
      - host: test.ingress.org
        http:
          paths:
          - backend:
              serviceName: test-service
              servicePort: 80