apiVersion: openmcp.k8s.io/v1alpha1
kind: OpenMCPJob
metadata:
  name: example-openmcpjob
  namespace: openmcp
spec:
  template:
    spec:
      backoffLimit: 5
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
          - name: pi
            image: perl
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: Never
