apiVersion: v1
kind: ConfigMap
metadata:
 namespace: metallb-system
 name: config
data:
 config: |
   address-pools:
   - name: default
     protocol: layer2
     addresses:
     - 10.0.3.241-10.0.3.250
     #- 192.168.1.240-192.168.1.250
