apiVersion: openmcp.k8s.io/v1alpha1
kind: Sync
metadata:
  name: openmcp-deployment-sync-3
  namespace: openmcp
spec:
  clustername: cluster1
  command: delete
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
      namespace: openmcp
